title: "My CTF Writeups"
description: "CTF challenge notes and walkthroughs."
plugins:
  - jekyll-seo-tag
markdown: kramdown
timezone: UTC
url: "https://writeups.claustra01.net"
baseurl: ""
collections:
  writeups:
    output: true
    permalink: /:name/
defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: writeup
      author: claustra01
