title: "claustra01 CTF Writeups"
description: "A collection of CTF writeups by claustra01."

plugins:
  - jekyll-seo-tag

markdown: kramdown
timezone: JST

url: "https://writeups.claustra01.net"
baseurl: ""

collections:
  writeups:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: writeups
    values:
      layout: writeup
      author: claustra01
