title: "My CTF Writeups"
description: "CTF challenge notes and walkthroughs."
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
markdown: kramdown
timezone: UTC
url: "https://writeups.claustra01.net"
baseurl: ""
collections:
  writeups:
    output: true
    permalink: /:collection/:name/
defaults:
  - scope:
      path: "_writeups"
      type: writeups
    values:
      layout: writeup
      author: your-handle
